FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env
WORKDIR /app

COPY *.sln ./
COPY ./*.csproj ./
COPY ./*.txt ./
RUN dotnet restore

COPY . ./
RUN dotnet publish ./MasterNodeAPI.csproj -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /app
# WEB_API_Port is 7090
EXPOSE 5001 7090
ENV ASPNETCORE_URLS=http://+:7090
COPY --from=build-env /app/out .
COPY ./*.txt .

ENTRYPOINT ["dotnet", "MasterNodeAPI.dll"]