FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env
WORKDIR /app

COPY *.sln ./
COPY ./*.csproj ./
RUN dotnet restore

COPY . ./
RUN dotnet publish ./ClientNode.csproj -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /app
EXPOSE 5001
COPY --from=build-env /app/out .

ENTRYPOINT ["dotnet", "ClientNode.dll"]